title: |md
  # TB Project Prototype Architecture
|

Downstream Consumers: {
  shape: image
  icon: https://icons.terrastruct.com/essentials%2F359-users.svg
}

PHAC: {
  Epidemiologists: {
    shape: image
    icon: https://icons.terrastruct.com/essentials%2F359-users.svg
  }
  Email: {
    "P/T Upstream Data": {
      shape: image
      icon: https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/119_Excel_logo_logos-512.png
    }
  }
}


PHAC.Epidemiologists -> PHAC.Email.P/T Upstream Data
PHAC.Email.P/T Upstream Data -> tb-analytics.Cloud Object Storage.tb-analytics: Users securely upload data to object storage

tb-analytics: {
  tb-analytics-iam: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FSecurity%2FCloud%20IAM.svg
  }
  Project Scope: {
    shape: image
    icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FDeveloper%20Tools%2FCloud%20SDK.svg
  }

  Cloud Object Storage: {
    "": {
      shape: image
      icon: https://icons.terrastruct.com/gcp%2FProducts%20and%20services%2FStorage%2FCloud%20Storage.svg
    }

    tb-analytics: {
      shape: image
      icon: https://icons.terrastruct.com/aws%2FStorage%2FAmazon-Simple-Storage-Service-S3_Bucket_light-bg.svg
    }

    tb-outputs: {
      shape: image
      icon: https://icons.terrastruct.com/aws%2FStorage%2FAmazon-Simple-Storage-Service-S3_Bucket_light-bg.svg
    }
  }

  Managed Notebook Service: {
    Managed Jupyterlab: {
      shape: image
      icon: https://jupyter.org/assets/homepage/main-logo.svg
    }

    Scheduled\/Manual Scripts: {
      shape: image
      icon: https://icons.terrastruct.com/dev%2Fpython.svg
    }
  }
  Cloud Object Storage.tb-analytics <-> Managed Notebook Service.Managed Jupyterlab: FUSE Mount to Filesystem
  Cloud Object Storage.tb-analytics <-> Managed Notebook Service.Scheduled\/Manual Scripts: FUSE Mount to Filesystem
  Managed Notebook Service.Managed Jupyterlab -> Cloud Object Storage.tb-outputs: Outputs, reports, etc.
  Managed Notebook Service.Scheduled\/Manual Scripts -> Cloud Object Storage.tb-outputs: Outputs, reports, etc.
}

tb-analytics.Cloud Object Storage.tb-outputs -> Downstream Consumers
