name: TB Jupyter Custom Image CI

on:
  push:
    branches:
      - main
    paths: 
      - 'jupyter-image/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Hadolint Action
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: ./jupyter-image/Dockerfile
        
    - name: "Set image name"
      run: |
        echo "IMAGE_NAME=jupyter-env" >> $GITHUB_ENV
        
    - name: Build an image from Dockerfile
      working-directory: jupyter-image
      run: |
          docker build -t $IMAGE_NAME .
          
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}
        format: 'json'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
        timeout: '30m'
