---
title: "TB Data Processing"
output: html_document
---


Divide into bins and count by Age group

```{r}
library(openxlsx)
df <- read.xlsx("tests/bcdata.xlsx", startRow = 1)
breaks <- c(0, 1, 4, 14, 24, 34, 44, 54, 64, 74, Inf) 
labels <- c('Less than 1 year old', '1 to 4 years old', '5 to 14 years old', '15 to 24 years old', '25 to 34 years old', '35 to 44 years old', '45 to 54 years old', '55 to 64 years old', '65 to 74 years old', '75 years and older')
df$AgeGroup <- cut(df$Age, breaks = breaks, labels = labels, right = FALSE, include.lowest = TRUE)
age_counts <- table(df$AgeGroup)
age_counts <- age_counts[order(names(age_counts))]
case_counts <- as.data.frame(age_counts)
colnames(case_counts) <- c("Age.group", "ActiveCasesCount")
print(case_counts)
```
```{r}
total_counts = read.xlsx("tests/demographics_data.xlsx", startRow=1)
total_counts$Age.group <- sub("^\\d+ - ", "", total_counts$Age.group)

merged_data <- merge(case_counts, total_counts, by = "Age.group", all.x = TRUE, all.y = TRUE)

merged_data$IncidenceRate <- merged_data$ActiveCasesCount / merged_data$Population

print(merged_data)

```

```{r}
crosstab <- xtabs( ~ Gender + Survey_Year, data = df)
print(crosstab)
```
```

